### ISSUE TITLE
out of Memory

### ISSUE THREAD

**Issue by shtse8** [amphp/artax#130] opened 2017-08-27 13:13 UTC
I am using Artax to replace Guzzle for non-blocking async requests.
everything works fine but I found that the memory usage is increased rapidly.

```php
$request = new Artax\Request($url, $method);

switch ($method) {
	case "POST":
		$request = $request->withHeader('Content-Type', 'application/json');
		$request = $request->withBody(json_encode($data));
		break;
}

$client = new Artax\DefaultClient;
$client->setOption(Artax\Client::OP_TRANSFER_TIMEOUT, 5000);
$response = yield $client->request($request);
$body = yield $response->getBody();
```

**Comment by kelunik** [comment] 2017-08-27 13:49
What are you doing afterwards? Are there multiple requests? A bit more code would be interesting, maybe you can provide a full example, so I can reproduce it?

**Comment by shtse8** [comment] 2017-08-27 13:56
I am working on a stock market project, that auto buy and sell orders. (>10 requests/second)
There are multiple requests at the same time. I was using Guzzle before, but Curl is blocking always.
https://github.com/guzzle/guzzle/issues/1127#issuecomment-325197503
So I have moved to this project. This project is working fine, but it eats lots of CPU. Btw, at least I can send the requests async in non-blocking way. But I found that the memory is going up very quick. and finally out of memory. I don't know what can I do, but I am sure there was no problem with Guzzle Curl.

**Comment by shtse8** [comment] 2017-08-27 13:57
Here is my code of sending request.
```php
protected function request($url, $method, $options) : Promise
{
	$deferred = new Deferred;
	
	/* Create Client - Singleton */
	if (!self::$guzzleClient) {
		$defaultRequestHeaders = [];
		$defaultRequestHeaders['User-Agent'] = 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Safari/537.36';
		
		$handler = new CurlMultiHandler();
		// Loop::repeat(0, function() use ($handler) {
			// $handler->tick();
		// });
		Loop::repeat(0, \Closure::bind(function () use (&$timer) {
			if (!empty($this->handles)) {
				$this->tick();
			}
		}, $handler, $handler));
		
		// $timer = Loop::repeat(0, \Closure::bind(function () use (&$timer) {
			// $this->tick();
			// if (empty($this->handles) && Promise\queue()->isEmpty()) {
				// Loop::cancel($timer);
			// }
		// }, $handler, $handler));
		
		self::$guzzleClient = new GuzzleClient([
			'headers' => $defaultRequestHeaders,
			'handler' => HandlerStack::create($handler),
			'connect_timeout' => 5,
			'read_timeout' => 5,
			'timeout' => 5
		]);
	}
	
	/* Send Request */
	self::$guzzleClient
		->requestAsync($method, $url, $options)
		->then(function($response) use ($deferred) {
			$deferred->resolve($response);
		})
		->otherwise(function($e) use ($deferred) {
			if ($e instanceof Throwable) {
				$deferred->fail($e);
			} else {
				$deferred->fail(new Exception($e));
			}
		});
		
	return $deferred->promise();
}


protected function api(string $method, string $path, array $query = [], array $data = [])
{
	$deferred = new Deferred();
	
	$host = $this->getMarketHost();
	if (is_null(self::$requestingCount[$host])) self::$requestingCount[$host] = 0;
	$trySend = function() use (&$trySend, $deferred, $host, $method, $path, $query, $data) {
		// echo "RequestSendingCount = ".self::$requestingCount."\n";
		try {
			if (self::$requestingCount[$host] > 7) {
				throw new Exception("Max Requesting Count Reached.");
			}

			++self::$requestingCount[$host];
			++$this->requestCount;
			
			$method = strtoupper($method);
			$baseQuery = [
				'AccessKeyId' => $this->accessKey,
				'SignatureMethod' => 'HmacSHA256',
				'SignatureVersion' => '2',
				'Timestamp' => gmdate("Y-m-d\TH:i:s", time())
			];
			
			/* Create Signature */
			$query = $baseQuery + $query;
			// $query['trade_password'] = "Ohcepmam712!";
			// $query['tradePassword'] = "19880605Lo";
			ksort($query);
			$signaturData = "{$method}\n{$host}\n{$path}\n".http_build_query($query);
			$signature = base64_encode(hash_hmac("sha256", $signaturData, $this->secretKey, true));
			$query['Signature'] = $signature;
			
			$url = Uri::create("https://{$host}", $path)->withQuery(http_build_query($query))->toString();

			
			// $this->printLog($method." ".$url);
			
			// $request = new Artax\Request($url, $method);
			
			// switch ($method) {
				// case "POST":
					// $request = $request->withHeader('Content-Type', 'application/json');
					// $request = $request->withBody(json_encode($data));
					// break;
			// }
			
			// $client = new Artax\DefaultClient;
			// $client->setOption(Artax\Client::OP_TRANSFER_TIMEOUT, 5000);
			// $response = yield $client->request($request);
			// $body = yield $response->getBody();
		
			$requestHeaders = [];
			$requestBody = null;
			switch ($method) {
				case "POST":
					$requestHeaders['Content-Type'] = "application/json";
					$requestBody = json_encode($data);
					break;
			}
			$response = yield $this->request($url, $method, [
				'headers' => $requestHeaders,
				'body' => $requestBody
			]);
			$body = $response->getBody();
			
			$result = json_decode($body, true);
			$deferred->resolve($result);
			
		} catch (Exception $e) {
			++self::$retryCount;
			Loop::delay(200, $trySend);
		} finally {
			--self::$requestingCount[$host];
		}
	};
	Loop::defer($trySend);
	
	return $deferred->promise();
}
```

**Comment by shtse8** [comment] 2017-08-27 13:59
I am using Guzzle now from avoiding memory leakage. But I would like to use Artax for real non-blocking async requests. The comment part is Artax.

**Comment by kelunik** [comment] 2017-08-27 19:43
```php
Loop::repeat(0, function() use ($handler) {
    $handler->tick();
});
```

^ That hogs your CPU. It's basically equivalent to `while (true) { $handler->tick(); }`.

Could you provide a script similar to your actual request scheduling with dummy requests to something like http://httpbin.org/?

**Comment by shtse8** [comment] 2017-08-27 20:15
For the Guzzle part, I've tested the following three codes. The CPU usage is the same.  (<10%)
```php
Loop::repeat(0, function() use ($handler) {
	$handler->tick();
});
```
```php
Loop::repeat(0, \Closure::bind(function () use (&$timer) {
	if (!empty($this->handles)) {
		$this->tick();
	}
}, $handler, $handler));
```
```php
$timer = Loop::repeat(0, \Closure::bind(function () use (&$timer) {
	$this->tick();
	if (empty($this->handles) && Promise\queue()->isEmpty()) {
		Loop::cancel($timer);
	}
}, $handler, $handler));
```

For the Artax Part, I will try to write a dummy program that eats lots of memory today later.

**Comment by kelunik** [comment] 2017-08-28 07:25
There's no way around CPU hogging if you have a repeat watcher with an interval of 0.

**Comment by kelunik** [comment] 2017-10-03 20:51
```php
if (self::$requestingCount[$host] > 7) {
	throw new Exception("Max Requesting Count Reached.");
}
```

^ That should fail the `$deferred` instead of directly throwing.

Do you have a full example that I can run that shows the memory increasing?

**Comment by shtse8** [comment] 2017-10-06 19:32
@kelunik It should throw a new exception to let the catch retry again as this promise will retry the request until the request is success.
I am using GuzzleHTTP now, so I haven't followed this thread. As I remember, for my several projects used Artax, it was out of memory and then be killed by OS if I keep running the program 3-4 days. For my best guess, it will always happen if you keep making requests for several days no matter how I coded. (I have 32G memory using Google Cloud) Some of my projects are very simple, and it just keep sending requests to get the ticker of stock market, still, OOM after few days.

**Comment by kelunik** [comment] 2017-10-06 19:43
@shtse8 How many requests do you make per minute?

**Comment by shtse8** [comment] 2017-10-07 14:22
@kelunik at least 1-7 requests per second

**Comment by kelunik** [comment] 2017-10-23 11:47
@shtse8 Have your requests been to a HTTPS site? In that case this has been fixed via https://github.com/amphp/artax/commit/698a78862805062254eef1f702423c3f6e9a7c47. Upgrading PHP will also solve it after the next version is out, because OpenSSL was leaking memory for parsed certificates.

**Comment by shtse8** [comment] 2017-10-24 21:18
@kelunik yet, I requested to a HTTPS site.

**Closed** 2017-10-25 05:23 UTC
