### ISSUE TITLE
Consider implementing PSR-7 ResponseInterface 

### ISSUE THREAD

**Issue by Bilge** [amphp/artax#165] opened 2018-04-14 23:45 UTC
Why not implement the PSR-7 [`ResponseInterface`](https://www.php-fig.org/psr/psr-7/#33-psrhttpmessageresponseinterface) instead of rolling your own response interface? The format of your interface is so similar to the standard interface already that it wouldn't be difficult to adapt, which begs the question, why not just use it so it's interoperable with more software?

**Comment by bwoebi** [comment] 2018-04-15 07:28
Duplicate of #101

**Closed by bwoebi** 2018-04-15 07:28 UTC

**Comment by Bilge** [comment] 2018-04-15 08:50
I think you're missing the point. I'm not asking you to do anything with *streams*, just the `ResponseInterface`, which you can definitely implement because it's just a dumb value object. I'm not asking you to implement the entire PSR, hence the title of this issue.

**Comment by Bilge** [comment] 2018-04-15 09:01
Oh, never mind... for some reason I didn't realize `getBody()` had to return a stream. That's pretty awful.
