### ISSUE TITLE
Client::OP_BINDTO option doesn't have any effect?

### ISSUE THREAD

**Issue by AlexanderMatveev** [amphp/artax#100] opened 2016-10-21 14:14 UTC
Looks like Client::OP_BINDTO option make no sense ☹
## Intro

Let's say I have two IP's: MY_FIRST_IP, MY_SECOND_IP.
## Trying bash curl to check IP interface works fine:

``` bash
curl --interface MY_SECOND_IP http://ip-api.com/json
```

result:

``` json
{ ... "query":"MY_SECOND_IP" ...}
```

Fine.
## Trying artax:

``` php
$client->request("http://ip-api.com/json", [
  Client::OP_BINDTO => 'MY_SECOND_IP',
]);
```

result:

``` json
{ ... "query":"MY_FIRST_IP" ...}
```

Gives MY_FIRST_IP instead of MY_SECOND_IP.

**Comment by kelunik** [comment] 2016-10-21 16:37
Confirmed. You can reproduce it locally by using the following Nginx configuration:

```nginx
server {
	listen 80 default_server;
	return 200 $remote_addr;
}
```

```php
<?php

require __DIR__ . "/vendor/autoload.php";

Amp\run(function () use ($argv) {
    $client = new Amp\Artax\Client;
    $client->setOption(Amp\Artax\Client::OP_BINDTO, $argv[1] ?? "");

    $response = yield $client->request("http://localhost/");

    var_dump($response->getBody());

    Amp\stop();
});
```

You can run it with `php test.php "127.0.0.1"` and `php test.php "$LOCAL_NETWORK_ADDR"`.

**Comment by kelunik** [comment] 2016-10-21 16:41
This seems like a PHP bug to me. [The documentation states that you can set the IP and / or port](http://php.net/manual/de/context.socket.php). Setting it to `192.168.1.100:0` works for me as expected, `192.168.1.100` just gets ignored.

**Comment by bwoebi** [comment] 2016-10-21 22:46
@kelunik It's not a PHP bug, just the docs are maybe a bit badly worded.

It requires input in format "ip:port", with both operands set. It's just that you can set one of them to 0.
I.e. valid, according to docs should be:
```
192.168.1.100:1234
192.168.1.100:0
0:1234
0:0
```
And invalid:
```
192.168.1.100
:1234
```

**Comment by AlexanderMatveev** [comment] 2016-10-22 07:40
PHP curl parameter CURLOPT_INTERFACE works fine, with just IP string, without port.

Docs say:
> CURLOPT_INTERFACE
> The name of the outgoing network interface to use. This can be an interface name, an IP address or a host name.

Now I'm using pure PHP curl with curl_multi_exec() http://php.net/manual/ru/function.curl-multi-exec.php instead of artax, in case of multithreaded requests it does everything I need 😊

**Comment by kelunik** [comment] 2016-10-22 08:05
@bwoebi I think we should either fix PHP or fix `amphp/socket` to automatically append `:0` if there's only an IP.

**Comment by bwoebi** [comment] 2016-10-22 11:01
@kelunik I agree there - on doing both, I think. Fix PHP (7.1) and amphp/socket because older versions.

**Comment by AlexanderMatveev** [comment] 2016-10-22 22:03
@kelunik @bwoebi Ok guys, thanks for response, I hope this report was useful.

**Comment by kelunik** [comment] 2017-01-18 16:56
@bwoebi Did you have a look at fixing this in php-src?

**Comment by kelunik** [comment] 2017-05-16 05:41
Closing, as I moved it to https://github.com/amphp/socket/issues/25.

**Closed by kelunik** 2017-05-16 05:41 UTC
Labels: bug
