### ISSUE TITLE
Feature/Question: Migrate Request/Uri classes to PSR-7

### ISSUE THREAD

**Issue by shrikeh** [amphp/artax#146] opened 2017-11-08 10:41 UTC
I've been extensively testing Artax for five minutes and I have _an opinion_.

Looking in the code, I see that Artax uses it's own `Request` class. While the `Response` in Artax does not look PSR-7able (real word), the Request/Uri appears to duplicate functionality available in PSR-7 libraries.

I would suggest that a future version of Artax dump it's own hand-rolled version of the `Request` in favour of something like using the `guzzlehttp\psr7` library, as it's not core to how Artax works, and not something that in reality Artax should care about or focus on.

Thoughts?

**Comment by kelunik** [comment] 2017-11-08 11:30
Duplicate of #101.

We could use `Uri`, but just pulling in PSR-7 for that doesn't make sense to me, as people will expect PSR-7 then, not just its `Uri` interface.

**Closed by kelunik** 2017-11-08 11:30 UTC

**Comment by shrikeh** [comment] 2017-11-08 11:47
I read #101 prior to posting and thought it that was more about the Response. In the case of Request and Uri, as these are setup pieces for Artax, I think they might be a better fit.

Actually looking at how the Response is generated, what was a major headache in implementing the PSR-7 ResponseInterface? I'm not clear from an extensive two minute readthrough what would be the major blocker.

**Comment by kelunik** [comment] 2017-11-08 12:49
How is the request different from the response? Both extend the [`MessageInterface`](http://www.php-fig.org/psr/psr-7/#31-psrhttpmessagemessageinterface) which contains the problematic `getBody()` that requires a `StreamInterface` implementation.

There's no headache. `StreamInterface` requires `getContents()` to return the remaining body directly as return value, which is just not possible without either blocking or fully buffering the response body.

**Comment by shrikeh** [comment] 2017-11-08 13:20
I'm not quite sure I follow on this. Certainly, the anonymous class I get back has a `getBody()` method, and I think we could have getContents() as a blocking action at that point (you have explicitly asked for the entirety of the contents by calling it, so this probably means that you _must_ block.

As to the difference between Request/URI and Response, the former two are more like value objects for setup as opposed to being particularly useful for data transfer. That is, whether an Artax Request, a PSR-7 Request, or an array, you could move around the values necessary to either configure an app or a client. The same is not strictly true for a Response, because they are either the expected return of your application (Web framework's job being at one level to populate a Response) or they are populated with unknown data from an external source.

**Comment by kelunik** [comment] 2017-11-08 14:37
Nothing I/O related should ever block in an asynchronous world. If you want the complete body, just call a method that returns a promise that resolves with the buffered contents once available. Same applies to the request bodies, which can also be streamed depending on the use case. If the remote is slow and doesn't clear its receive buffer fast enough, Artax will automatically throttle the request body streaming as well, because its own write buffer will become full at some point.

**Comment by shrikeh** [comment] 2017-11-08 14:46
OK, now I follow the problem. That does make implementing every part of PSR-7 for Response tricky.

Returning to Request and Uri, however, these are used by Artax as strongly typed configuration payloads. I can't really see a problem with _accepting_ them (the argument parameter IIRC is called `$uriOrRequest`, and then interrogated for type. I would say people coming across amphp are probably not the sort to get confused by Requests, but that's possibly my own bias.

There seems like a couple of options:

- Do nothing. Bask in your glory. Relax with a stern yet paternal face as you watch people using your cool library. The world remains good.
- Accept in PSR-7 Uris or Requests as arguments, extract what you need from them, use your own Request internally. So, an effective bridge/data normalizer.
- Have your Request implement PSR-7 directly.
- Find a library you like that is small and has a Request object implementation you like. Grin in victory as you never have to write another test for a Request get method.

**Comment by kelunik** [comment] 2017-11-08 15:38
Oh, we could indeed probably _accept_ them, additionally. It's basically just providing an adapter within the `Client`. We can't change the signature of `Client` as that's a BC break, but we could probably change the signature of `DefaultClient` and make it accept those.

On the other hand, that's not something a `Client` should really care about. I think I'll reduce the signature to only accepting `Request` in v4 to have proper type declarations available. I also plan to remove a lot of functionality from the client and pack that into middlewares, as that makes it way easier to extend and maintain.
