### ISSUE TITLE
Request hangs with keep alive and non-native loop driver

### ISSUE THREAD

**Issue by brstgt** [amphp/artax#138] opened 2017-10-05 12:38 UTC
Sometimes requests hang infinetely (or until socket is closed remotely). Insights so far:
Request hangs in read loop in DefaultClient::doRead after header is received. Normally it hangs in the last response chunk. Symptom before hang: 0 bytes are read from reader stream (ResourceInputStream) and then the socket never becomes readable again.

Script to reproduce:

https://gist.github.com/brstgt/3533deadce54dac4d1807a01de6f2d82

Problem normally appears after 10-200 iterations.

IMPORTANT: Problem does NOT occur if connection is not keep-alive (header 'Connection: close') OR if the NativeDriver is used

**Comment by kelunik** [comment] 2017-10-05 12:49
The issue is that it tries to read from a broken socket. `NativeDriver` reports that as readable, but the other drivers don't.

**Comment by brstgt** [comment] 2017-10-05 13:10
I know this is not a fix but I simply wanted to test it:

If i put this in ResourceInputStream watcher readable callback, it does not hang:

            $data = @\fread($stream, $chunkSize);

            while (strlen($data) == 0) {
	            $data = @\fread($stream, $chunkSize);
            }

**Comment by kelunik** [comment] 2017-10-05 13:11
When running with `strace` there are quite a lot of `Resource is temporarily unavailable` errors with `EAGAIN`.

**Comment by bwoebi** [comment] 2017-10-06 00:14
https://github.com/amphp/byte-stream/blob/master/lib/ResourceInputStream.php#L56

Not sure, but what's that feof() check doing there? Looks completely superfluous to me.

**Comment by kelunik** [comment] 2017-10-06 06:52
@bwoebi Without that there are issues with OpenSSL I guess, because a stream might be readable, but OpenSSL isn't ready to give you a chunk yet.

**Comment by kelunik** [comment] 2017-10-06 07:21
Confirmed, without it you get an instant: `Amp\Artax\SocketException: Socket disconnected prior to response completion (Parser state: 0)`

**Comment by brstgt** [comment] 2017-10-06 07:23
During tests I observed very frequently the case that 0 bytes have been
read but the socket is still alive and on next read, some data arrives.

2017-10-06 9:21 GMT+02:00 Niklas Keller <notifications@github.com>:

**Comment by kelunik** [comment] 2017-10-06 15:39
Only works with `stream_select` because of https://lxr.room11.org/xref/php-src%40master/ext/standard/streamsfuncs.c#stream_array_emulate_read_fd_set

I built PHP with a `printf` in there to make sure that it takes that path. So it's definitely an issue with PHP buffering data.

**Comment by kelunik** [comment] 2017-10-07 10:40
#139 fixed the long hang and applies the timeout correctly now, but it's not a fix for the `onReadable` not being triggered, yet.

**Comment by kelunik** [comment] 2017-10-08 10:46
Resolved via `amphp/byte-stream` v1.1.5.

**Closed by kelunik** 2017-10-08 10:46 UTC
Labels: bug

**Comment by mmenozzi** [comment] 2017-11-27 18:09
Hi guys,
I have a similar problem but it happens in a very weird manner so I don't think is related to this issue but the error message is the same: `Socket disconnected prior to response completion (Parser state: 0)`. I'll explain the whole story.

I have a Mac Book Pro as a development machine and I have a simply Apache + PHP + MySQL setup. I have to work on several projects so to speedup the setup of every new project I configured Apache with `VirtualDocumentRoot` directive (here an example of my configuration http://roberto-montero.com/blog/how-setup-xampp-use-virtualdocumentroot-mac-os-x). I have also a virtual host configured for `localhost` whose document root is the root of my workspace (the directory which contains all of my projects, `~/Work/Projects`).
So if go to `http://localhost/phpinfo.php`, I get the phpinfo located in the root of all my projects (`~/Work/Projects/phpinfo.php`). Instead if I go to `http://myproject.dev/phpinfo.php` I get the phpinfo located in the directory of "myproject" (`~/Work/Projects/myproject/phpinfo.php`).

Ok, given this scenario, I wanted to use this async HTTP client to perform HTTP requests against a project which I'm working on.

So I installed artax using composer and simply copy & pasted your example n. 1 (https://github.com/amphp/artax/blob/master/examples/1-get-request.php) to perform a simple GET request.

First I tried with the URL provided in the example (`https://httpbin.org/user-agent`) and it worked.
But then, I tried with my local project using the URL `http://myproject.dev/phpinfo.php`, and this last trial **didn't work**. I got the error `Socket disconnected prior to response completion (Parser state: 0)`.
After several trials I figured out that if I use `http://localhost/phpinfo.php` **it works**. So I tried with several different request to other resources/projects and the pattern that I found is that:

- Requests to resources under `http://localhost/` are **working**
- Requests to resources under `VirtualDocumentRoot` virtual hosts (like `http://myproject.dev/`) are not working.

Please note that all of them are served from my dev machine (so Apache is the same, PHP is the same, etc...) and all my trials are with the same sample script.

So it seems (but I would like to confirm) that there is some weird circumstance that cause that error only if use a `VirtualDocumentRoot` virtual host.

Now, I would like to understand what the f**k is going on but I have no idea where to start. Do you guys have any suggestion? 😄 

Thank you.

**Comment by kelunik** [comment] 2017-11-27 18:21
@mmenozzi Please open a separate issue for that.

**Comment by mmenozzi** [comment] 2017-11-27 18:42
Done @kelunik : #150
